# Generated by Django 3.0.5 on 2020-04-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Event Name', max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('approx_funds', models.IntegerField(default=5000)),
                ('location', models.CharField(default='Club House', max_length=100)),
            ],
        ),
    ]
