# Generated by Django 3.0.5 on 2020-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200422_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_filled',
            field=models.BooleanField(default=False),
        ),
    ]
